### ISSUE TITLE
Griefing by self trading

### ISSUE THREAD

**Issue by abandeali1** [plutoegg/token_deposit_wrapper#1]
At the moment, a token owner can still move the token by creating a signed order with another account and then filling it. This can be fixed by adding `require(tx.origin == ETHFINEX)` to `transferFrom`, assuming the centralized matching model is used.

Note that there are some open questions about the functionality of tx.origin post account abstraction: https://github.com/ethereum/EIPs/issues/637

**Comment by kingcocomango** [comment]
Will fix by requiring the exchange to be a party in any transfers.

The contract aims to be a commitment to a tradeable balance, not a fully fledged token.
