### ISSUE TITLE
Support multiple signers

### ISSUE THREAD

**Issue by abandeali1** [plutoegg/token_deposit_wrapper#2]
Instead of hard coding in a single address that can sign withdrawal requests, we can have a mapping of addresses to bool for approved signers. This makes the contract more upgradeable and provides flexibility for distributing workload among servers that are signing with different private keys.

**Comment by plutoegg** [comment]
Will include this as a change, with
`mapping (address => bool) isSigner`
and `isSigner(ecrecover(...`

Plus a function for the addition of new signers by existing signers (tbd)
